package scenarios.cyclomaticComplexityEvaluation.complexExpressions;

import java.io.IOException;

import org.json.simple.parser.ParseException;

import SPLComplexityEvaluation.SPLDecoratorComplexityComparator;
import astFileProcessor.annotationManagment.astConstructs.NotFoundBlockElementToWrap;
import astFileProcessor.processors.cyclomaticComplexity.ExpressionsForCyclomaticComplexityManipulationSettings;
import codeConstructsEvaluation.transformation.ComplexityService;
import scenarios.Scenario;
import unsupportedDecoratorsManagement.NonExistingDecoratorTransformationType;
import unsupportedDecoratorsManagement.entities.IllegalImportNameSpecifiedException;



public class Scenario1HierarchicConfigurationExpressionsEval {
	
	public Scenario1HierarchicConfigurationExpressionsEval() {}
	
	public void launchScenario() throws NonExistingDecoratorTransformationType, IOException, IllegalImportNameSpecifiedException, NotFoundBlockElementToWrap, ParseException {
		SPLDecoratorComplexityComparator splCyclomaticComplexityComparator = Scenario.getDefaultCyclomaticComplexityComparatorFullyFetaureTreeExpressions();
		ExpressionsForCyclomaticComplexityManipulationSettings nativeConfExpressionsConf 
			= TransformationFormsForCyclomaticComplexityFullTree.getConditionalFlowWithNativeConditions();
		ExpressionsForCyclomaticComplexityManipulationSettings entireConfExpressionsAsJsonConf
			= TransformationFormsForCyclomaticComplexityFullTree.getConditionalFlowWithEntireHierarchicExpression(true);
		splCyclomaticComplexityComparator.compareComplexityForScenario(
				nativeConfExpressionsConf, entireConfExpressionsAsJsonConf);
	}
	
	public void launchScenario(String pathToProjectTree, ComplexityService complexityService)
			   throws NonExistingDecoratorTransformationType, IOException, IllegalImportNameSpecifiedException, NotFoundBlockElementToWrap, ParseException {
		SPLDecoratorComplexityComparator splCyclomaticComplexityComparator = Scenario.getDefaultCyclomaticComplexityComparator(pathToProjectTree, complexityService);
		ExpressionsForCyclomaticComplexityManipulationSettings nativeConfExpressionsConf = TransformationFormsForCyclomaticComplexityFullTree.getConditionalFlowWithNativeConditions();
		ExpressionsForCyclomaticComplexityManipulationSettings confExpressionsLayersAsJsonConf = 
			TransformationFormsForCyclomaticComplexityFullTree.getConditionalFlowWithEntireHierarchicExpression(true);
		splCyclomaticComplexityComparator.compareComplexityForScenario(
				nativeConfExpressionsConf, confExpressionsLayersAsJsonConf);
	}

	public static void main(String args[]) throws NonExistingDecoratorTransformationType, IOException, IllegalImportNameSpecifiedException, NotFoundBlockElementToWrap, ParseException {
		Scenario1HierarchicConfigurationExpressionsEval scenarioConfigurationExpressionsEval = new Scenario1HierarchicConfigurationExpressionsEval();
		scenarioConfigurationExpressionsEval.launchScenario();
	}
}